import { RuvelKey } from './types';

export const RUVEL_KEYS: RuvelKey[] = [
  { id: 'first_touch', name: 'First Touch', emoji: '🔑', description: 'Primera clase completada', type: 'auto', milestone: 1 },
  { id: 'rising_star', name: 'Rising Star', emoji: '🔑', description: '5 clases completadas', type: 'auto', milestone: 5 },
  { id: 'diamond_hands', name: 'Diamond Hands', emoji: '💎', description: '10 clases completadas', type: 'auto', milestone: 10 },
  { id: 'chord_hero', name: 'Chord Hero', emoji: '🔑', description: 'Tocó un acorde perfectamente', type: 'manual' },
  { id: 'song_slayer', name: 'Song Slayer', emoji: '🔑', description: 'Completó su primera canción entera', type: 'manual' },
  { id: 'on_fire', name: 'On Fire', emoji: '🔑', description: 'Tarea 3 semanas seguidas', type: 'manual' },
  { id: 'module_master', name: 'Module Master', emoji: '🔑', description: 'Completó un módulo entero', type: 'manual' },
  { id: 'natural_ear', name: 'Natural Ear', emoji: '🎵', description: 'Oído excepcional para la música', type: 'manual' },
  { id: 'performance_ready', name: 'Performance Ready', emoji: '🎭', description: 'Interpretó una canción', type: 'manual' },
];

export interface Module {
  id: number;
  title: string;
  titleEn: string;
  icon: string;
  description: string;
  phase: 'Fundamentos' | 'Construcción' | 'Avanzado';
  keySkills: string[];
  estimatedWeeks: string;
  kids: { approach: string; notes: string; };
  youth: { approach: string; notes: string; };
  adults: { approach: string; notes: string; };
  exercises: string[];
  songs?: string[];
  lessonGuide?: string[];
  progressChecklist?: string[];
}

// ─── RÜVEL METHOD — 16-MODULE BILINGUAL CURRICULUM ──────────────────────────
// Filosofía: acordes primero (chord-first), fórmulas no memorización,
// canciones reales desde el día 1, teoría después de la práctica, orden estricto.
export const MODULES: Module[] = [
  // ═══ FUNDAMENTOS ═══════════════════════════════════════════════════════
  {
    id: 1,
    title: 'Primer Contacto',
    titleEn: 'First Touch',
    icon: '🎹',
    description: 'Introducción al piano — postura, números de dedos (finger numbers) y geografía del teclado (keyboard geography). La base sobre la que se construye todo.',
    phase: 'Fundamentos',
    keySkills: ['Postura correcta (posture)', 'Números de dedos 1-5', 'Geografía del teclado', 'Encontrar todas las notas Do (C)', 'Tocar Do-Sol (C-G) con digitación correcta'],
    estimatedWeeks: '1-2 semanas',
    kids: {
      approach: 'Teclas con colores y nombres divertidos para los dedos',
      notes: 'Usa nombres de animales para las notas: Do=Conejo, Re=Ratón, Mi=Mono, Fa=Foca, Sol=Sapo, La=León, Si=Serpiente. Sesiones de 30 min máx. Todo como juego o reto.',
    },
    youth: {
      approach: '"Tus manos son el control" (the controller)',
      notes: 'La técnica como superpoder — buena postura = aprender más rápido. Responden a retos: "¿Qué tan rápido encuentras todos los Do?"',
    },
    adults: {
      approach: 'Explica el PORQUÉ desde el inicio',
      notes: 'La postura previene lesiones — esto le importa a los adultos. Explica el patrón de teclas blancas y negras, por qué el teclado se repite cada octava (octave).',
    },
    exercises: [
      'Calentamiento de dedos: 1-2-3-4-5, 5-4-3-2-1',
      'Encontrar TODAS las notas Do (C) en el teclado',
      'Tocar Do-Re-Mi-Fa-Sol (C-D-E-F-G) con digitación correcta',
      'Posición de Do: pulgar en Do, tocar hasta Sol',
      'Introducir posición de descanso y dedos curvos',
    ],
    lessonGuide: [
      'Semana 1: empieza con la postura — altura del banco, muñeca, dedos curvos. Usa la imagen del "huevo en la mano".',
      'Introduce los números de dedos 1-5 en ambas manos.',
      'Geografía del teclado: grupos de 2 y 3 teclas negras. Encuentra el Do a la izquierda del grupo de 2 negras.',
      'Toca Do-Re-Mi-Fa-Sol con la mano derecha, pulgar en Do.',
      'Semana 2: repasa, toca melodías simples de 5 notas.',
    ],
    progressChecklist: [
      'Se sienta con postura correcta y altura de banco adecuada',
      'Conoce los números de dedos 1-5 en ambas manos',
      'Encuentra todas las notas Do (C) sin dudar',
      'Encuentra todas las notas Sol (G)',
      'Toca Do-Re-Mi-Fa-Sol con digitación correcta (1-2-3-4-5)',
      'Mantiene los dedos curvos al tocar',
      'Entiende los grupos de 2 y 3 teclas negras',
    ],
  },
  {
    id: 2,
    title: 'Acordes Mágicos',
    titleEn: 'Magic Chords',
    icon: '✨',
    description: 'Los 4 acordes mágicos — Do, Sol, Lam, Fa (C, G, Am, F) — que desbloquean cientos de canciones. Fórmulas mayor y menor que funcionan en cualquier tonalidad.',
    phase: 'Fundamentos',
    keySkills: ['Acorde de Do mayor (C major)', 'Acorde de Sol mayor (G major)', 'Acorde de Lam (A minor)', 'Acorde de Fa mayor (F major)', 'Fórmula mayor: raíz+4+3 semitonos', 'Fórmula menor: raíz+3+4 semitonos', 'Notación americana de acordes'],
    estimatedWeeks: '2-3 semanas',
    kids: {
      approach: '"Desbloqueo de superpoder" — un acorde por clase',
      notes: 'Cada acorde nuevo es un "superpoder desbloqueado". Hazlo un momento grande. El juego Chord Story funciona muy bien aquí.',
    },
    youth: {
      approach: '"Estos 4 acordes = 90% del pop"',
      notes: 'Muéstrales una canción conocida apenas aprendan los acordes. La progresión I-V-vi-IV desbloquea: Let Her Go, Someone Like You, Riptide, Hallelujah.',
    },
    adults: {
      approach: 'Conexión teórica — la progresión I-V-vi-IV',
      notes: 'Explica POR QUÉ estos acordes funcionan juntos. Fórmula mayor = raíz + 4 semitonos + 3 semitonos. Menor = raíz + 3 + 4. Conéctalo al Sistema de Números de Nashville.',
    },
    exercises: [
      'Construir Do mayor desde la fórmula: Do + Mi + Sol (C+E+G)',
      'Construir Sol mayor: Sol + Si + Re (G+B+D)',
      'Construir Lam desde la fórmula menor: La + Do + Mi (A+C+E)',
      'Construir Fa mayor: Fa + La + Do (F+A+C)',
      'Transiciones de acordes: Do → Sol → Lam → Fa',
      'Tocar los 4 acordes con una base rítmica simple',
    ],
    lessonGuide: [
      'Introduce la fórmula del acorde mayor — raíz + 4 semitonos + 3 semitonos.',
      'Construyan Do mayor juntos. Tóquenlo como una unidad.',
      'Repasa Do mayor. Introduce Sol mayor con la misma fórmula.',
      'Fórmula menor = raíz + 3 + 4. Construir Lam. Comparar Lam con La mayor.',
      'Construir Fa mayor. Practicar los 4 en secuencia: Do → Sol → Lam → Fa.',
      'Transiciones fluidas. Tocar junto a una canción.',
    ],
    progressChecklist: [
      'Conoce la fórmula del acorde mayor (raíz + 4 + 3 semitonos)',
      'Conoce la fórmula del acorde menor (raíz + 3 + 4 semitonos)',
      'Toca Do mayor (C) correctamente de memoria',
      'Toca Sol mayor (G) correctamente de memoria',
      'Toca Lam (Am) correctamente de memoria',
      'Toca Fa mayor (F) correctamente de memoria',
      'Transiciona Do → Sol → Lam → Fa con fluidez',
      'Toca la secuencia de 4 acordes sin parar',
    ],
    songs: ['Let Her Go', 'Someone Like You', 'Riptide', "Can't Help Falling in Love", 'Hallelujah'],
  },
  {
    id: 3,
    title: 'Ritmo y Groove',
    titleEn: 'Rhythm & Groove',
    icon: '🥁',
    description: 'El latido de la música. Pulso vs ritmo (pulse vs rhythm), uso del metrónomo, y los patrones de mano izquierda que hacen que las canciones cobren vida.',
    phase: 'Fundamentos',
    keySkills: ['Pulso vs ritmo', 'Uso del metrónomo (metronome)', 'Patrones de mano izquierda', 'Compases (time signatures)', 'Valores de las notas (note values)'],
    estimatedWeeks: '2-3 semanas',
    kids: {
      approach: 'Percusión corporal primero — juegos de palmas',
      notes: '"El latido de la canción" — que encuentren el pulso en canciones que aman. Palmas, zapateo, percusión corporal antes de tocar el piano.',
    },
    youth: {
      approach: 'Conéctalo a la música que conocen',
      notes: 'Muestra cómo funciona el beat drop en EDM. Los patrones de trap. Ya sienten el ritmo — ahora ponle nombre.',
    },
    adults: {
      approach: 'Teoría — compases y subdivisión',
      notes: '4/4, 3/4, 6/8 explicados bien. Valores: redonda, blanca, negra, corchea. La subdivisión como clave para sentir el ritmo. Disciplina con el metrónomo.',
    },
    exercises: [
      'Aplaudir junto a una canción, encontrar el pulso',
      'Tocar negras con metrónomo a 60 BPM',
      'Mano izquierda: pulso constante de negras en Do',
      'Patrón de mano izquierda: Do-Sol-Do-Sol alternando',
      'Tocar acordes en los tiempos 1 y 3',
      'Introducir patrones simples de notas de bajo',
    ],
    lessonGuide: [
      'Abre con percusión corporal: aplaude un ritmo, que el estudiante lo repita.',
      'Introduce el compás 4/4: 4 tiempos por compás, negra = 1 tiempo.',
      'Introducción al metrónomo: empieza a 60 BPM.',
      'Mano izquierda con pulso constante mientras la derecha toca melodía.',
      'Patrón de mano izquierda: Do-Sol alternando (raíz-quinta).',
      'Tocar una canción simple con MI constante + MD melodía.',
    ],
    progressChecklist: [
      'Encuentra y aplaude el pulso de cualquier canción',
      'Entiende la diferencia entre pulso y ritmo',
      'Cuenta 1-2-3-4 con precisión mientras toca',
      'Toca con metrónomo a 60 BPM sin perder el tiempo',
      'La mano izquierda mantiene un pulso constante de negras',
      'Toca el patrón Do-Sol alternado con la mano izquierda',
      'Entiende los valores: redonda, blanca, negra, corchea',
    ],
  },
  {
    id: 4,
    title: 'Intervalos',
    titleEn: 'Intervals',
    icon: '📏',
    description: 'El ADN de la música. La distancia entre dos notas — segundas, terceras, cuartas, quintas, sextas, séptimas y octavas (2nds → octaves). Todo acorde y escala está hecho de intervalos.',
    phase: 'Fundamentos',
    keySkills: ['Contar semitonos (semitones / half steps)', 'Nombrar intervalos: 2ª, 3ª, 4ª, 5ª, 6ª, 7ª, 8ª', 'Intervalos mayores vs menores', 'Reconocer intervalos de oído', 'Intervalos consonantes vs disonantes'],
    estimatedWeeks: '2-3 semanas',
    kids: {
      approach: '"Saltos" entre notas — cerca o lejos',
      notes: 'Para niños: un intervalo es un "salto". Salto pequeño (2ª) o salto grande (8ª). Usa canciones famosas: el inicio de "Brilla Brilla" salta una 5ª. Hazlo visual y físico.',
    },
    youth: {
      approach: 'Reconocer intervalos en sus canciones favoritas',
      notes: 'Cada intervalo tiene un "sonido". La 8ª = "Somewhere Over the Rainbow". La 5ª = tema de Star Wars. La 4ª = "Here Comes the Bride". Asocia cada intervalo a una canción que ya conocen.',
    },
    adults: {
      approach: 'La lógica matemática de los intervalos',
      notes: 'Un intervalo se mide en semitonos. 3ª mayor = 4 semitonos, 3ª menor = 3. Esto conecta directamente con las fórmulas de acordes que ya saben. Los adultos aman ver el sistema completo.',
    },
    exercises: [
      'Contar semitonos entre dos notas cualquiera',
      'Tocar e identificar 2ª, 3ª, 4ª y 5ª desde Do',
      'Comparar 3ª mayor (4 semitonos) vs 3ª menor (3 semitonos)',
      'Tocar la octava (octave) y la quinta justa (perfect 5th)',
      'Entrenamiento de oído: adivinar el intervalo que suena',
      'Asociar cada intervalo a una canción famosa',
    ],
    lessonGuide: [
      'Define intervalo: la distancia entre dos notas, medida en semitonos.',
      'Empieza con la 2ª (notas vecinas) y la octava (mismo nombre, más agudo).',
      'Construye 3ª, 4ª y 5ª desde Do. Cuenta los semitonos en voz alta.',
      'Distingue mayor vs menor: 3ª mayor (4 semitonos) suena alegre, 3ª menor (3) suena triste.',
      'Conecta con los acordes: un acorde mayor = 3ª mayor + 3ª menor apiladas.',
      'Entrenamiento de oído: toca un intervalo, el estudiante adivina cuál es.',
    ],
    progressChecklist: [
      'Cuenta semitonos entre dos notas con precisión',
      'Nombra los intervalos 2ª, 3ª, 4ª, 5ª, 6ª, 7ª y 8ª',
      'Distingue una 3ª mayor de una 3ª menor',
      'Toca una octava y una quinta justa correctamente',
      'Reconoce de oído al menos 4 intervalos',
      'Entiende que un acorde está hecho de intervalos apilados',
    ],
    songs: ['Twinkle Twinkle Little Star', 'Somewhere Over the Rainbow', 'Star Wars (Main Theme)', 'Jaws Theme'],
  },
  {
    id: 5,
    title: 'La Escala Mayor',
    titleEn: 'The Major Scale',
    icon: '🪜',
    description: 'La escala mayor (major scale) — la fórmula T-T-S-T-T-T-S (whole-half steps) que crea el sonido "alegre" base de casi toda la música occidental. La regla maestra para construir cualquier escala.',
    phase: 'Fundamentos',
    keySkills: ['Fórmula de la escala mayor: T-T-S-T-T-T-S', 'Construir la escala de Do mayor', 'Digitación de escalas (paso del pulgar)', 'Grados de la escala (scale degrees 1-7)', 'Tónica, dominante, sensible'],
    estimatedWeeks: '2-3 semanas',
    kids: {
      approach: 'La escala como una "escalera de sonidos"',
      notes: 'Una escala es una escalera: subes nota por nota hasta llegar arriba. Usa Do-Re-Mi de "La Novicia Rebelde" (The Sound of Music). Que la canten mientras la tocan.',
    },
    youth: {
      approach: 'La escala es de donde salen TODAS las melodías',
      notes: 'Las melodías de sus canciones favoritas viven dentro de la escala. Si conocen la escala, pueden sacar canciones de oído. Eso los motiva mucho.',
    },
    adults: {
      approach: 'La fórmula universal: T-T-S-T-T-T-S',
      notes: 'Tono-Tono-Semitono-Tono-Tono-Tono-Semitono. Esta única fórmula construye las 12 escalas mayores. Explica los grados: tónica (1), dominante (5), sensible (7).',
    },
    exercises: [
      'Construir Do mayor con la fórmula T-T-S-T-T-T-S',
      'Tocar la escala de Do mayor con digitación correcta (1-2-3-1-2-3-4-5)',
      'Practicar el paso del pulgar (thumb crossover)',
      'Construir la escala de Sol mayor (aparece el Fa#)',
      'Tocar la escala con metrónomo, subiendo y bajando',
      'Numerar los grados de la escala (1 a 7)',
    ],
    lessonGuide: [
      'Presenta la fórmula: Tono-Tono-Semitono-Tono-Tono-Tono-Semitono.',
      'Construyan Do mayor aplicando la fórmula tecla por tecla.',
      'Digitación: 1-2-3 luego pasa el pulgar para 1-2-3-4-5.',
      'Practica el paso del pulgar en aislado — debe ser silencioso y suave.',
      'Aplica la fórmula a Sol: aparece el primer sostenido, Fa#.',
      'Numera los grados: 1=tónica, 5=dominante, 7=sensible. Estos nombres importan luego.',
    ],
    progressChecklist: [
      'Conoce la fórmula de la escala mayor (T-T-S-T-T-T-S)',
      'Construye la escala de Do mayor desde la fórmula',
      'Toca la escala de Do mayor con digitación correcta',
      'Ejecuta el paso del pulgar de forma suave',
      'Construye la escala de Sol mayor (con Fa#)',
      'Identifica los grados de la escala (tónica, dominante, etc.)',
    ],
    songs: ['Joy to the World', 'Do-Re-Mi', 'Ode to Joy'],
  },
  // ═══ CONSTRUCCIÓN ══════════════════════════════════════════════════════
  {
    id: 6,
    title: 'Mundo Mayor y Menor',
    titleEn: 'Major & Minor World',
    icon: '🌍',
    description: 'Los 12 acordes mayores y 12 menores. La diferencia emocional entre mayor y menor — y el CARÁCTER de cada tonalidad (key emotions): por qué Re mayor suena triunfal y Mi menor melancólico.',
    phase: 'Construcción',
    keySkills: ['Los 12 acordes mayores', 'Los 12 acordes menores', 'Dominio de las fórmulas de acordes', 'Cualidad emocional de los acordes', 'Carácter emocional de cada tonalidad'],
    estimatedWeeks: '3-4 semanas',
    kids: {
      approach: 'Conexión emocional — sonidos "felices" vs "tristes"',
      notes: 'Toca un acorde mayor — "¿Cómo se siente?" Toca el menor — "¿Y ahora?" Lo entienden al instante. Mapea emociones a acordes.',
    },
    youth: {
      approach: 'Construir cualquier acorde desde cualquier nota',
      notes: 'Aquí se sienten músicos de verdad. Pueden tocar CUALQUIER acorde. Los acordes menores tienen más profundidad emocional — perfectos para pop/indie.',
    },
    adults: {
      approach: 'Construcción sistemática en las 12 tonalidades',
      notes: 'Cada tonalidad tiene un carácter: Do mayor = puro/simple, Re mayor = brillante/triunfal, Mi menor = melancólico, La menor = introspectivo. Conéctalo a la teoría del afecto.',
    },
    exercises: [
      'Construir los 12 acordes mayores desde la fórmula',
      'Construir los 12 acordes menores desde la fórmula',
      'Tocar Rem, Mim, Sim, Fa#m (Dm, Em, Bm, F#m)',
      'Comparar Lam vs La mayor emocionalmente',
      'Tocar una progresión en menor: Lam-Fa-Do-Sol',
      'Identificar mayor vs menor de oído',
    ],
    lessonGuide: [
      'Repasa la fórmula de Do mayor. Aplícala a Re: Re-Fa#-La.',
      'Trabaja primero los sostenidos: Sol, Re, La, Mi, Si, Fa# mayor.',
      'Luego los bemoles: Fa, Sib, Mib, Lab, Reb mayor.',
      'Acordes menores: repasa Lam. Prueba Rem, Mim, Sim.',
      'Contraste emocional: toca Do mayor → Do menor. Discutan el cambio de ánimo.',
      'Carácter de las tonalidades: explora cómo cada tonalidad "se siente" distinta.',
    ],
    progressChecklist: [
      'Construye cualquier acorde mayor desde la fórmula',
      'Construye cualquier acorde menor desde la fórmula',
      'Conoce los nombres de los 12 acordes mayores',
      'Conoce los nombres de los 12 acordes menores',
      'Identifica mayor vs menor de oído con seguridad',
      'Toca la progresión menor Lam-Fa-Do-Sol con fluidez',
      'Describe el carácter emocional de al menos 4 tonalidades',
    ],
  },
  {
    id: 7,
    title: 'Armaduras y Círculo de Quintas',
    titleEn: 'Key Signatures & Circle of Fifths',
    icon: '🔵',
    description: 'Las armaduras (key signatures) — cuántos sostenidos o bemoles tiene cada tonalidad — y el Círculo de Quintas (Circle of Fifths), el mapa maestro que organiza las 12 tonalidades.',
    phase: 'Construcción',
    keySkills: ['Leer armaduras (sostenidos y bemoles)', 'El Círculo de Quintas', 'Orden de sostenidos: Fa-Do-Sol-Re-La-Mi-Si', 'Orden de bemoles: Si-Mi-La-Re-Sol-Do-Fa', 'Tonalidades relativas (mayor/menor)'],
    estimatedWeeks: '2-3 semanas',
    kids: {
      approach: 'El círculo como un "reloj de tonalidades"',
      notes: 'Para niños, simplifica: el Círculo de Quintas es como un reloj donde cada hora es una tonalidad. Enfócate solo en Do, Sol y Fa al principio.',
    },
    youth: {
      approach: 'El "código secreto" para entender cualquier canción',
      notes: 'Las armaduras te dicen en qué tonalidad está una canción. Si saben leer la armadura, saben qué notas y acordes esperar. Es un atajo poderoso.',
    },
    adults: {
      approach: 'El mapa maestro de toda la música',
      notes: 'El Círculo de Quintas conecta todo: tonalidades vecinas, acordes que suenan bien juntos, transposición, modulación. Es la herramienta más poderosa de la teoría musical.',
    },
    exercises: [
      'Identificar la armadura de Do, Sol, Re y Fa',
      'Memorizar el orden de los sostenidos (Fa-Do-Sol-Re-La-Mi-Si)',
      'Memorizar el orden de los bemoles (Si-Mi-La-Re-Sol-Do-Fa)',
      'Recorrer el Círculo de Quintas en sentido horario',
      'Encontrar la tonalidad menor relativa de cada tonalidad mayor',
      'Determinar la tonalidad de una canción por su armadura',
    ],
    lessonGuide: [
      'Explica qué es una armadura: los sostenidos/bemoles al inicio del pentagrama.',
      'Presenta el Círculo de Quintas — dibújenlo juntos.',
      'En sentido horario se agrega un sostenido; en antihorario, un bemol.',
      'Orden de sostenidos: Fa-Do-Sol-Re-La-Mi-Si ("Father Charles Goes Down...").',
      'Orden de bemoles: el orden inverso.',
      'Tonalidades relativas: cada mayor comparte armadura con una menor.',
    ],
    progressChecklist: [
      'Lee la armadura de las tonalidades comunes',
      'Recita el orden de los sostenidos',
      'Recita el orden de los bemoles',
      'Recorre el Círculo de Quintas en ambos sentidos',
      'Encuentra la tonalidad menor relativa de cualquier mayor',
      'Determina la tonalidad de una canción por su armadura',
    ],
  },
  {
    id: 8,
    title: 'Inversiones y Voicings',
    titleEn: 'Chord Inversions & Voicings',
    icon: '🔄',
    description: 'Las inversiones de acordes (chord inversions) — el mismo acorde con las notas reordenadas. Posición fundamental, 1ª y 2ª inversión, y cómo elegir voicings para cambios de acorde suaves.',
    phase: 'Construcción',
    keySkills: ['Posición fundamental (root position)', 'Primera inversión (1st inversion)', 'Segunda inversión (2nd inversion)', 'Conducción de voces (voice leading)', 'Elegir el voicing más cercano'],
    estimatedWeeks: '2-3 semanas',
    kids: {
      approach: 'El mismo acorde con las notas "rebajadas"',
      notes: 'Toma la nota de abajo del acorde y súbela una octava — ¡es el mismo acorde, pero suena distinto! Hazlo como un juego de reordenar.',
    },
    youth: {
      approach: 'El truco para que los acordes suenen profesionales',
      notes: 'Las inversiones hacen que los cambios de acorde sean suaves — sin saltos torpes. Es lo que separa a un principiante de alguien que suena pulido.',
    },
    adults: {
      approach: 'Conducción de voces — el arte de mover poco',
      notes: 'La regla de oro: al cambiar de acorde, mueve la menor cantidad de notas posible. Eso es voice leading. Explica cómo el bajo (la nota más grave) cambia el carácter del acorde.',
    },
    exercises: [
      'Tocar Do mayor en posición fundamental, 1ª y 2ª inversión',
      'Recorrer las 3 posiciones de los 4 acordes mágicos',
      'Conectar Do → Sol usando inversiones (movimiento mínimo)',
      'Tocar la progresión Do-Sol-Lam-Fa con voicings cercanos',
      'Identificar qué inversión se está tocando',
      'Voicing abierto vs cerrado (open vs closed)',
    ],
    lessonGuide: [
      'Explica: una inversión es el mismo acorde con otra nota en el bajo.',
      'Do mayor: fundamental = Do-Mi-Sol, 1ª inv = Mi-Sol-Do, 2ª inv = Sol-Do-Mi.',
      'Practica las 3 posiciones, luego cicla entre ellas sin parar.',
      'Conducción de voces: conecta Do → Sol moviendo lo mínimo posible.',
      'Aplica a la progresión Do-Sol-Lam-Fa con voicings cercanos — escucha lo suave que suena.',
      'Voicing abierto vs cerrado: separa las notas para un sonido más amplio.',
    ],
    progressChecklist: [
      'Toca cualquier acorde en posición fundamental, 1ª y 2ª inversión',
      'Cicla entre las 3 posiciones sin parar',
      'Usa inversiones para conectar acordes suavemente',
      'Toca Do-Sol-Lam-Fa con voicings cercanos',
      'Identifica de oído/vista qué inversión se toca',
      'Entiende el concepto de conducción de voces',
    ],
  },
  {
    id: 9,
    title: 'Ambas Manos',
    titleEn: 'Both Hands',
    icon: '🙌',
    description: 'El hito más grande — las manos trabajando juntas. Melodía con la mano derecha, acordes o bajo con la izquierda. Independencia de manos (hand independence).',
    phase: 'Construcción',
    keySkills: ['Independencia de manos', 'Melodía + acompañamiento', 'Ejercicios de coordinación', 'Canciones con ambas manos'],
    estimatedWeeks: '3-5 semanas',
    kids: {
      approach: 'Una mano a la vez, luego lento juntas',
      notes: 'Practica cada mano por separado hasta que sea automática. Luego combina MUY lento. Celebra cada pequeño logro.',
    },
    youth: {
      approach: 'Canciones geniales hacen que valga el esfuerzo',
      notes: 'Elige una canción que de verdad quieran tocar. La lucha de la independencia vale la pena cuando logran algo impresionante.',
    },
    adults: {
      approach: 'Practicar lento es aprender rápido',
      notes: 'Explica la ciencia: la práctica lenta construye conexiones neuronales. 50% de velocidad hasta que sea perfecto, LUEGO acelera.',
    },
    exercises: [
      'Mano derecha melodía, mano izquierda se queda en Do',
      'Ejercicios de manos alternadas (MI-MD-MI-MD)',
      'Canción simple: MD melodía + MI notas raíz',
      'Ejercicio de coordinación: ritmos distintos en cada mano',
      'Tocar Himno a la Alegría con ambas manos, lento',
    ],
    lessonGuide: [
      'Explica la independencia de manos: cada mano es un músico aparte.',
      'Ejercicio: MD toca melodía, MI sostiene Do. Foco 100% en la MD.',
      'Toques alternados: MI en el 1, MD en el 2, etc.',
      'Elige una canción simple. Semana 1: solo MD. Semana 2: solo MI. Semana 3: combinar al 50%.',
      'Práctica lenta = práctica precisa.',
      'Celebra: la primera vez con ambas manos, aunque sean 4 compases, es un gran logro.',
    ],
    progressChecklist: [
      'Toca la melodía con la MD limpia, sin que la MI la distraiga',
      'Toca el acompañamiento de la MI limpio, sin la MD',
      'Toca el Himno a la Alegría con ambas manos (aunque sea lento)',
      'Mantiene un ritmo constante con ambas manos',
      'Toca una canción completa con ambas manos',
      'Entiende la metodología de práctica lenta',
    ],
  },
  {
    id: 10,
    title: 'Lectura Musical',
    titleEn: 'Reading Music',
    icon: '📖',
    description: 'Leer partituras de verdad. Clave de Sol Y clave de Fa (treble & bass clef), el pentagrama doble (grand staff), valores de notas y silencios, y la lectura a primera vista.',
    phase: 'Construcción',
    keySkills: ['Clave de Sol (treble clef)', 'Clave de Fa (bass clef)', 'Pentagrama doble (grand staff)', 'Valores de notas y silencios', 'Solfeo: Do Re Mi Fa Sol La Si', 'Lectura a primera vista'],
    estimatedWeeks: '4-6 semanas',
    kids: {
      approach: 'Canciones de solfeo y trucos de memoria',
      notes: 'Trucos para las líneas y espacios. Solfeo con Do-Re-Mi. Los niños que aprenden nombres de notas Y solfeo desarrollan mejor intuición musical.',
    },
    youth: {
      approach: 'Leer como superpoder para aprender canciones rápido',
      notes: 'Leer música = un cheat code: puedes aprender cualquier canción escrita. Muéstrales la partitura de una canción que aman.',
    },
    adults: {
      approach: 'Enfoque sistemático con música real',
      notes: 'Empieza con los valores completos, ve construyendo. Usa música que reconozcan. Las flashcards ayudan mucho.',
    },
    exercises: [
      'Nombrar las notas en las líneas y espacios de la clave de Sol',
      'Nombrar las notas de la clave de Fa (la mano izquierda)',
      'Leer el pentagrama doble (grand staff) completo',
      'Solfeo: cantar Do Re Mi Fa Sol La Si',
      'Aplaudir el ritmo antes de tocar',
      'Leer y tocar una pieza simple a primera vista',
    ],
    lessonGuide: [
      'Dibujen la clave de Sol juntos. Líneas: Mi-Sol-Si-Re-Fa. Espacios: Fa-La-Do-Mi.',
      'Introduce la clave de Fa para la mano izquierda. Líneas: Sol-Si-Re-Fa-La.',
      'Une las dos claves en el pentagrama doble — el Do central las conecta.',
      'Solfeo: Do=C, Re=D, Mi=E... canta subiendo y bajando.',
      'Valores: redonda (4), blanca (2), negra (1), corchea (½). Aplaudir antes de tocar.',
      'Lectura a primera vista: nombra las notas, aplaude el ritmo, toca lento.',
    ],
    progressChecklist: [
      'Nombra las notas de la clave de Sol (líneas y espacios)',
      'Nombra las notas de la clave de Fa',
      'Lee el pentagrama doble completo',
      'Canta el solfeo Do-Re-Mi-Fa-Sol-La-Si afinado',
      'Lee correctamente negras, blancas, redondas y silencios',
      'Aplaude los ritmos antes de tocarlos',
      'Lee a primera vista una pieza simple a tempo lento',
    ],
  },
  // ═══ AVANZADO ══════════════════════════════════════════════════════════
  {
    id: 11,
    title: 'Acordes de Séptima y Color',
    titleEn: 'Seventh Chords & Color',
    icon: '🎨',
    description: 'Más allá de las 3 notas. Acordes de séptima (maj7, m7, dom7), disminuidos, aumentados, suspendidos y extendidos (9, 11, 13). El color y la sofisticación de la armonía moderna.',
    phase: 'Avanzado',
    keySkills: ['Séptima mayor (maj7)', 'Séptima menor (m7)', 'Séptima de dominante (dom7)', 'Acordes disminuidos y aumentados (dim, aug)', 'Acordes suspendidos (sus2, sus4)', 'Extensiones: 9, 11, 13'],
    estimatedWeeks: '3-4 semanas',
    kids: {
      approach: 'Acordes con "sabor" extra',
      notes: 'Para niños, simplifica: una 4ª nota le da "sabor" al acorde. Enfócate solo en el sonido — el maj7 suena "soñador", el dom7 suena "con ganas de moverse".',
    },
    youth: {
      approach: 'Los acordes que usan sus artistas favoritos',
      notes: 'El neo-soul, el R&B, el lo-fi — todos viven de los acordes de séptima. Es el sonido "aesthetic" que aman. Muéstrales el maj7 y m7 primero.',
    },
    adults: {
      approach: 'El color de la armonía sofisticada',
      notes: 'Una 7ª transforma un acorde simple en algo expresivo. dom7 = tensión que quiere resolver. maj7 = belleza relajada. dim7 = drama. Conéctalo al jazz y al cine.',
    },
    exercises: [
      'Construir Domaj7 (Cmaj7): Do-Mi-Sol-Si',
      'Construir Rem7 (Dm7): Re-Fa-La-Do',
      'Construir Sol7 (G7, dominante): Sol-Si-Re-Fa',
      'Tocar acordes disminuidos y aumentados',
      'Tocar acordes sus2 y sus4 y resolverlos',
      'Introducir extensiones de novena (add9)',
    ],
    lessonGuide: [
      'Repasa el acorde tríada. Ahora agrega una 4ª nota: la séptima.',
      'maj7: tríada mayor + 7ª mayor. Domaj7 = Do-Mi-Sol-Si. Suena soñador.',
      'm7: tríada menor + 7ª menor. Rem7 = Re-Fa-La-Do. Suena suave.',
      'dom7: tríada mayor + 7ª menor. Sol7 = Sol-Si-Re-Fa. Crea tensión.',
      'Disminuidos y aumentados: para drama y transiciones.',
      'Suspendidos: sus4 reemplaza la 3ª — suena "abierto", quiere resolver.',
    ],
    progressChecklist: [
      'Construye y toca un acorde maj7',
      'Construye y toca un acorde m7',
      'Construye y toca un acorde dom7',
      'Toca acordes disminuidos y aumentados',
      'Toca acordes sus2 y sus4 y los resuelve',
      'Entiende qué "color" aporta cada tipo de séptima',
    ],
  },
  {
    id: 12,
    title: 'Escalas Menores y Modos',
    titleEn: 'Minor Scales & Modes',
    icon: '🌒',
    description: 'Las tres escalas menores (natural, armónica, melódica) y los 7 modos (Jónico, Dórico, Frigio, Lidio, Mixolidio, Eólico, Locrio). Cada uno con su propio color emocional.',
    phase: 'Avanzado',
    keySkills: ['Escala menor natural', 'Escala menor armónica', 'Escala menor melódica', 'Los 7 modos griegos', 'El color emocional de cada modo'],
    estimatedWeeks: '4-5 semanas',
    kids: {
      approach: 'Escalas con "personalidades" distintas',
      notes: 'Para niños, mantenlo simple: la escala menor suena "misteriosa". No es necesario cubrir los 7 modos con niños pequeños — enfócate en menor natural.',
    },
    youth: {
      approach: 'Los modos como "filtros de emoción"',
      notes: 'Cada modo es un filtro: Dórico = cool/jazzy, Frigio = español/oscuro, Lidio = mágico/de ensueño. Muéstrales modos en bandas sonoras de videojuegos y cine.',
    },
    adults: {
      approach: 'El sistema completo de modos',
      notes: 'Cada modo es la escala mayor empezando desde un grado distinto. Dórico = desde el 2º grado. Explica cómo esto abre un universo de colores melódicos.',
    },
    exercises: [
      'Tocar la escala menor natural de La (A natural minor)',
      'Tocar la menor armónica (con la 7ª elevada)',
      'Tocar la menor melódica (6ª y 7ª elevadas al subir)',
      'Tocar el modo Dórico de Re (D Dorian)',
      'Tocar el modo Mixolidio de Sol (G Mixolydian)',
      'Comparar el color emocional de cada modo',
    ],
    lessonGuide: [
      'Menor natural: la escala menor base. Lam natural = teclas blancas desde La.',
      'Menor armónica: eleva la 7ª — crea ese sonido "exótico" y la tensión hacia la tónica.',
      'Menor melódica: eleva la 6ª y 7ª al subir, naturales al bajar.',
      'Los modos: cada uno es la escala mayor empezando en un grado distinto.',
      'Dórico (2º grado), Frigio (3º), Lidio (4º), Mixolidio (5º), Eólico (6º), Locrio (7º).',
      'Explora el color: toca cada modo y describe la emoción que transmite.',
    ],
    progressChecklist: [
      'Toca la escala menor natural',
      'Toca la escala menor armónica',
      'Toca la escala menor melódica',
      'Toca al menos 3 de los 7 modos',
      'Explica de dónde sale cada modo (qué grado de la escala mayor)',
      'Describe el color emocional de los modos principales',
    ],
  },
  {
    id: 13,
    title: 'Armonía y Progresiones',
    titleEn: 'Harmony & Progressions',
    icon: '🧩',
    description: 'El lenguaje de las progresiones. Números romanos (Roman numerals), funciones armónicas (tónica, subdominante, dominante), cadencias y las progresiones que mueven a la música.',
    phase: 'Avanzado',
    keySkills: ['Números romanos (I-ii-iii-IV-V-vi-vii°)', 'Funciones: tónica, subdominante, dominante', 'Cadencias (auténtica, plagal, rota)', 'Progresiones comunes del pop y el jazz', 'Análisis armónico de canciones'],
    estimatedWeeks: '4-5 semanas',
    kids: {
      approach: 'Los acordes como "personajes de una historia"',
      notes: 'Para niños, simplifica: el acorde I es "el hogar", el V es "la aventura", y volver al I es "llegar a casa". No abrumes con números romanos formales.',
    },
    youth: {
      approach: 'Descifrar el código de sus canciones favoritas',
      notes: 'Una vez que entienden los números romanos, pueden analizar cualquier canción y ver que comparten las mismas progresiones. Es revelador y poderoso.',
    },
    adults: {
      approach: 'El sistema que explica TODA la música',
      notes: 'Los números romanos vuelven la armonía universal — independiente de la tonalidad. I-V-vi-IV funciona igual en cualquier tono. Cadencias = puntuación musical.',
    },
    exercises: [
      'Numerar los acordes de la escala de Do (I-ii-iii-IV-V-vi-vii°)',
      'Identificar las funciones: tónica (I), subdominante (IV), dominante (V)',
      'Tocar una cadencia auténtica (V-I)',
      'Tocar una cadencia plagal (IV-I)',
      'Tocar la progresión I-V-vi-IV en 3 tonalidades distintas',
      'Analizar una canción real con números romanos',
    ],
    lessonGuide: [
      'Numera los acordes de la escala: mayúsculas = mayor, minúsculas = menor.',
      'En Do: I=Do, ii=Rem, iii=Mim, IV=Fa, V=Sol, vi=Lam, vii°=Sim°.',
      'Funciones: el I es estabilidad, el IV se aleja, el V crea tensión que vuelve al I.',
      'Cadencia auténtica V-I: la resolución más fuerte, el "punto final".',
      'Cadencia plagal IV-I: la resolución "amén", más suave.',
      'Analiza canciones reales: descubre que el I-V-vi-IV está en todas partes.',
    ],
    progressChecklist: [
      'Numera los 7 acordes de una tonalidad mayor con números romanos',
      'Identifica las funciones tónica, subdominante y dominante',
      'Toca y reconoce una cadencia auténtica (V-I)',
      'Toca y reconoce una cadencia plagal (IV-I)',
      'Transpone la progresión I-V-vi-IV a varias tonalidades',
      'Analiza una canción real con números romanos',
    ],
  },
  {
    id: 14,
    title: 'Pedal, Dinámica y Expresión',
    titleEn: 'Pedal, Dynamics & Expression',
    icon: '🦶',
    description: 'Lo que convierte las notas en MÚSICA. El pedal de resonancia (sustain pedal), la dinámica (piano/forte), la articulación (legato/staccato) y el fraseo musical.',
    phase: 'Avanzado',
    keySkills: ['Técnica del pedal de resonancia', 'Dinámica: pp, p, mp, mf, f, ff', 'Reguladores (crescendo/diminuendo)', 'Articulación: legato, staccato', 'Fraseo y respiración musical'],
    estimatedWeeks: '3-4 semanas',
    kids: {
      approach: 'El pedal como "magia" y tocar "fuerte/suave"',
      notes: 'El pedal hace que el sonido "flote". Juega con tocar como un ratón (suave) y como un elefante (fuerte). La expresión como juego de personajes.',
    },
    youth: {
      approach: 'La diferencia entre sonar "bien" y sonar "increíble"',
      notes: 'Las notas correctas no bastan. La dinámica y el fraseo son lo que da emoción. Comparen la misma frase tocada plana vs tocada con expresión.',
    },
    adults: {
      approach: 'El detalle profesional de la interpretación',
      notes: 'El pedal sincronizado con el cambio de armonía (pedal legato). La dinámica como narrativa. El fraseo como respiración. Aquí la música se vuelve arte.',
    },
    exercises: [
      'Técnica del pedal: bajar después de tocar (pedal legato/sincopado)',
      'Tocar una escala de pp a ff y de regreso',
      'Practicar crescendo y diminuendo en una progresión',
      'Contrastar la misma frase en legato y en staccato',
      'Frasear una melodía con "respiraciones" musicales',
      'Aplicar pedal + dinámica a una balada completa',
    ],
    lessonGuide: [
      'Introduce el pedal de resonancia: cómo levanta los apagadores y deja sonar las cuerdas.',
      'Técnica del pedal legato: toca la nota PRIMERO, luego baja el pedal, súbelo al cambiar de armonía.',
      'Dinámica: explica la escala pp-p-mp-mf-f-ff. Usa el peso del brazo, no la fuerza.',
      'Crescendo y diminuendo: el volumen como una ola.',
      'Articulación: legato (conectado) vs staccato (corto). Exagera el contraste.',
      'Fraseo: la música respira. Aplica todo a una balada real.',
    ],
    progressChecklist: [
      'Usa el pedal de resonancia con la técnica legato (sincopada)',
      'Controla la dinámica desde pp hasta ff',
      'Ejecuta crescendo y diminuendo de forma gradual',
      'Distingue y toca legato vs staccato',
      'Frasea una melodía con sentido musical',
      'Aplica pedal, dinámica y fraseo a una pieza completa',
    ],
  },
  {
    id: 15,
    title: 'Dominio de Canciones',
    titleEn: 'Song Mastery',
    icon: '🎸',
    description: 'Aprender canciones completas de principio a fin. Práctica por secciones, método de lento a rápido, y la confianza para interpretar.',
    phase: 'Avanzado',
    keySkills: ['Aprender canciones completas', 'Práctica por secciones', 'Método de lento a rápido', 'Confianza interpretativa', 'Técnicas de memorización'],
    estimatedWeeks: '4-8 semanas',
    kids: {
      approach: 'Su canción favorita como meta principal',
      notes: 'Pregunta qué canción sueñan con tocar. Divídela en partes alcanzables. Mini "conciertos" para los padres dan confianza.',
    },
    youth: {
      approach: 'La canción que de verdad querrían compartir',
      notes: 'Algo que tocarían para sus amigos. Aquí empiezan a sentirse músicos de verdad. Graba su progreso.',
    },
    adults: {
      approach: 'Una canción significativa con conexión emocional',
      notes: 'A menudo una canción ligada a un recuerdo. Divídela en secciones de 4 compases. Domina cada una antes de conectar.',
    },
    exercises: [
      'Dividir la canción elegida en 4 secciones',
      'Practicar cada sección con manos separadas',
      'Unir las secciones cuando cada una esté limpia',
      'Grabar la práctica y analizar los errores',
      'Tocar la canción completa al 50%, 75% y velocidad real',
      'Interpretar para un público imaginario',
    ],
    lessonGuide: [
      'Elijan la canción juntos. Si dudan, ofrece 3 opciones.',
      'Mapea la estructura: intro, verso, coro, puente. Etiqueta secciones A, B, C.',
      'Domina la Sección A con manos separadas, a tempo lento.',
      'Agrega la Sección B. Cuando A+B esté limpio, conéctalas.',
      'Pasadas completas. Graba en el teléfono. Escucha con criterio.',
      'Clase final: mini-interpretación. Toca toda la canción, haz una reverencia.',
    ],
    progressChecklist: [
      'Conoce la estructura de la canción (intro, verso, coro, etc.)',
      'Toca la Sección A con manos separadas, limpia',
      'Toca la Sección B con manos separadas, limpia',
      'Conecta las secciones A+B con fluidez',
      'Toca la canción completa con ambas manos',
      'Toca la canción completa al tempo objetivo',
      'Interpretó la canción para al menos una persona',
    ],
  },
  {
    id: 16,
    title: 'Exprésate',
    titleEn: 'Express Yourself',
    icon: '🎤',
    description: 'Improvisación, composición y encontrar tu propia voz musical. Aquí el piano se vuelve verdaderamente personal.',
    phase: 'Avanzado',
    keySkills: ['Improvisar sobre acordes', 'Crear melodías', 'Estilo personal', 'Fundamentos de composición', 'Ejercicios de creatividad'],
    estimatedWeeks: '4+ semanas (continuo)',
    kids: {
      approach: 'Componer una canción corta con su nombre',
      notes: 'El juego Improvisation Dice. Ejercicios de "toca la emoción". Que compongan una pieza de 4 compases y le pongan título.',
    },
    youth: {
      approach: 'Improvisar sobre sus progresiones favoritas',
      notes: 'Usa la escala pentatónica sobre acordes menores primero. Muéstrales cómo improvisan sus artistas favoritos.',
    },
    adults: {
      approach: 'Conversación musical y autoexpresión',
      notes: 'Muchos adultos soñaron con componer de niños. Este módulo lo cumple. Empieza con improvisación de 4 compases sobre Do-Sol-Lam-Fa.',
    },
    exercises: [
      'Improvisar usando solo la escala pentatónica de Do',
      'Crear una melodía de 4 compases sobre Do-Sol-Lam-Fa',
      'Improvisation Dice: tonalidad + ánimo + tempo al azar',
      'Sacar de oído una frase de 2 compases de una canción',
      'Componer una pieza corta y ponerle título',
    ],
    lessonGuide: [
      'Introduce la pentatónica mayor de Do: Do-Re-Mi-Sol-La. Siempre suena bien.',
      'Toca el loop Do-Sol-Lam-Fa. El estudiante improvisa solo con la pentatónica.',
      'Ejercicio de composición: "inventa una melodía de 4 compases".',
      'Avanzado: pentatónica menor sobre Lam-Fa-Do-Sol.',
      'Llamada y respuesta: el profe toca 2 compases, el estudiante "responde".',
      'Proyecto final: componer una pieza completa de 8 compases con título.',
    ],
    progressChecklist: [
      'Conoce y toca la escala pentatónica de Do',
      'Improvisa libremente sobre los 4 acordes mágicos',
      'Compuso al menos una melodía original de 4 compases',
      'Toca de oído — saca melodías simples',
      'Entiende la improvisación de llamada y respuesta',
      'Interpretó una composición original',
    ],
  },
];

export interface Song {
  id: string;
  title: string;
  artist: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  genre: string;
  module: number;
  ageGroup: string;
}

export const SONGS: Song[] = [
  // ── MÓDULO 1 — PRIMER CONTACTO (5-finger / melodías simples) ─────────────
  { id: 's1', title: 'Twinkle Twinkle Little Star', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's2', title: 'Happy Birthday', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's3', title: 'Mary Had a Little Lamb', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's4', title: 'Hot Cross Buns', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's6', title: 'Baa Baa Black Sheep', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's7', title: 'London Bridge', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's8', title: 'Row Row Row Your Boat', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's10', title: 'Old MacDonald', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's11', title: 'Itsy Bitsy Spider', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's300', title: 'Jingle Bells (melodía)', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's301', title: 'You Are My Sunshine', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's302', title: 'Frère Jacques (Brother John)', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },
  { id: 's303', title: 'Skip to My Lou', artist: 'Traditional', difficulty: 'Beginner', genre: 'Kids', module: 1, ageGroup: 'Kids' },

  // ── MÓDULO 2 — ACORDES MÁGICOS (pop de 4 acordes) ────────────────────────
  { id: 's14', title: 'Someone Like You', artist: 'Adele', difficulty: 'Beginner', genre: 'Pop', module: 2, ageGroup: 'Any' },
  { id: 's15', title: 'Riptide', artist: 'Vance Joy', difficulty: 'Beginner', genre: 'Indie Pop', module: 2, ageGroup: 'Any' },
  { id: 's16', title: 'Let Her Go', artist: 'Passenger', difficulty: 'Beginner', genre: 'Folk Pop', module: 2, ageGroup: 'Any' },
  { id: 's17', title: 'Hallelujah', artist: 'Leonard Cohen', difficulty: 'Beginner', genre: 'Folk', module: 2, ageGroup: 'Any' },
  { id: 's18', title: "Can't Help Falling in Love", artist: 'Elvis Presley', difficulty: 'Beginner', genre: 'Classic Pop', module: 2, ageGroup: 'Any' },
  { id: 's20', title: 'Payphone', artist: 'Maroon 5', difficulty: 'Beginner', genre: 'Pop', module: 2, ageGroup: 'Any' },
  { id: 's23', title: 'Tenerife Sea', artist: 'Ed Sheeran', difficulty: 'Beginner', genre: 'Pop', module: 2, ageGroup: 'Any' },
  { id: 's24', title: "I'm Yours", artist: 'Jason Mraz', difficulty: 'Beginner', genre: 'Pop', module: 2, ageGroup: 'Any' },
  { id: 's26', title: 'Stand By Me', artist: 'Ben E. King', difficulty: 'Beginner', genre: 'Classic Soul', module: 2, ageGroup: 'Adults' },
  { id: 's200', title: 'Love Yourself', artist: 'Justin Bieber', difficulty: 'Beginner', genre: 'Pop', module: 2, ageGroup: 'Any' },
  { id: 's201', title: 'Photograph', artist: 'Ed Sheeran', difficulty: 'Beginner', genre: 'Pop', module: 2, ageGroup: 'Any' },
  { id: 's304', title: 'Wonderwall', artist: 'Oasis', difficulty: 'Beginner', genre: 'Rock', module: 2, ageGroup: 'Any' },
  { id: 's305', title: 'Ho Hey', artist: 'The Lumineers', difficulty: 'Beginner', genre: 'Folk Pop', module: 2, ageGroup: 'Any' },
  { id: 's306', title: 'Apologize', artist: 'OneRepublic', difficulty: 'Beginner', genre: 'Pop', module: 2, ageGroup: 'Any' },
  { id: 's307', title: 'Stay (piano)', artist: 'Rihanna ft. Mikky Ekko', difficulty: 'Beginner', genre: 'Pop', module: 2, ageGroup: 'Any' },

  // ── MÓDULO 3 — RITMO Y GROOVE ────────────────────────────────────────────
  { id: 's30', title: 'Another One Bites the Dust', artist: 'Queen', difficulty: 'Beginner', genre: 'Rock', module: 3, ageGroup: 'Any' },
  { id: 's34', title: 'Use Somebody (intro)', artist: 'Kings of Leon', difficulty: 'Beginner', genre: 'Rock', module: 3, ageGroup: 'Youth' },
  { id: 's35', title: 'Pompeii', artist: 'Bastille', difficulty: 'Beginner', genre: 'Pop Rock', module: 3, ageGroup: 'Youth' },
  { id: 's37', title: 'Shape of You (piano)', artist: 'Ed Sheeran', difficulty: 'Beginner', genre: 'Pop', module: 3, ageGroup: 'Any' },
  { id: 's38', title: 'Mr. Brightside (piano)', artist: 'The Killers', difficulty: 'Beginner', genre: 'Rock', module: 3, ageGroup: 'Youth' },
  { id: 's39', title: 'Seven Nation Army (piano)', artist: 'The White Stripes', difficulty: 'Beginner', genre: 'Rock', module: 3, ageGroup: 'Any' },
  { id: 's202', title: 'Bad Guy', artist: 'Billie Eilish', difficulty: 'Beginner', genre: 'Pop', module: 3, ageGroup: 'Youth' },
  { id: 's203', title: 'Despacito (groove)', artist: 'Luis Fonsi', difficulty: 'Beginner', genre: 'Latin', module: 3, ageGroup: 'Any' },
  { id: 's308', title: 'Superstition (piano)', artist: 'Stevie Wonder', difficulty: 'Beginner', genre: 'Funk Soul', module: 3, ageGroup: 'Any' },
  { id: 's309', title: 'Happy', artist: 'Pharrell Williams', difficulty: 'Beginner', genre: 'Pop', module: 3, ageGroup: 'Any' },
  { id: 's310', title: 'Uptown Funk (piano riff)', artist: 'Bruno Mars', difficulty: 'Beginner', genre: 'Funk', module: 3, ageGroup: 'Any' },
  { id: 's311', title: 'Levitating (piano)', artist: 'Dua Lipa', difficulty: 'Beginner', genre: 'Pop', module: 3, ageGroup: 'Youth' },

  // ── MÓDULO 4 — INTERVALOS (canciones famosas por sus intervalos) ─────────
  { id: 's210', title: 'Somewhere Over the Rainbow', artist: 'Harold Arlen', difficulty: 'Beginner', genre: 'Classic', module: 4, ageGroup: 'Any' },
  { id: 's211', title: 'Star Wars (Main Theme)', artist: 'John Williams', difficulty: 'Intermediate', genre: 'Film Score', module: 4, ageGroup: 'Any' },
  { id: 's212', title: 'Jaws Theme', artist: 'John Williams', difficulty: 'Beginner', genre: 'Film Score', module: 4, ageGroup: 'Any' },
  { id: 's213', title: 'Here Comes the Bride', artist: 'Wagner', difficulty: 'Beginner', genre: 'Classical', module: 4, ageGroup: 'Any' },
  { id: 's214', title: 'My Heart Will Go On (intro)', artist: 'Celine Dion', difficulty: 'Beginner', genre: 'Pop', module: 4, ageGroup: 'Any' },
  { id: 's312', title: 'When the Saints Go Marching In', artist: 'Traditional', difficulty: 'Beginner', genre: 'Gospel Jazz', module: 4, ageGroup: 'Any' },
  { id: 's313', title: 'Beethoven 5ª Sinfonía (apertura)', artist: 'Beethoven', difficulty: 'Beginner', genre: 'Classical', module: 4, ageGroup: 'Any' },

  // ── MÓDULO 5 — LA ESCALA MAYOR (melodías escalares) ──────────────────────
  { id: 's5', title: 'Ode to Joy', artist: 'Beethoven (simplified)', difficulty: 'Beginner', genre: 'Classical', module: 5, ageGroup: 'Any' },
  { id: 's215', title: 'Joy to the World', artist: 'Traditional', difficulty: 'Beginner', genre: 'Classical', module: 5, ageGroup: 'Any' },
  { id: 's216', title: 'Do-Re-Mi', artist: 'The Sound of Music', difficulty: 'Beginner', genre: 'Musical', module: 5, ageGroup: 'Kids' },
  { id: 's13', title: 'Go Tell Aunt Rhody', artist: 'Traditional', difficulty: 'Beginner', genre: 'Classical', module: 5, ageGroup: 'Any' },
  { id: 's217', title: 'Lava (intro)', artist: 'Disney Pixar', difficulty: 'Beginner', genre: 'Film', module: 5, ageGroup: 'Kids' },
  { id: 's314', title: 'Amazing Grace', artist: 'Traditional', difficulty: 'Beginner', genre: 'Gospel', module: 5, ageGroup: 'Any' },
  { id: 's315', title: 'La Bamba (melodía)', artist: 'Traditional / Ritchie Valens', difficulty: 'Beginner', genre: 'Latin', module: 5, ageGroup: 'Any' },
  { id: 's316', title: 'Oh! Susanna', artist: 'Stephen Foster', difficulty: 'Beginner', genre: 'Folk', module: 5, ageGroup: 'Any' },

  // ── MÓDULO 6 — MUNDO MAYOR Y MENOR ───────────────────────────────────────
  { id: 's40', title: 'Blinding Lights (simplified)', artist: 'The Weeknd', difficulty: 'Intermediate', genre: 'Pop', module: 6, ageGroup: 'Any' },
  { id: 's41', title: 'Believer', artist: 'Imagine Dragons', difficulty: 'Intermediate', genre: 'Pop Rock', module: 6, ageGroup: 'Youth' },
  { id: 's43', title: 'Mad World', artist: 'Gary Jules', difficulty: 'Intermediate', genre: 'Alternative', module: 6, ageGroup: 'Any' },
  { id: 's49', title: 'Demons', artist: 'Imagine Dragons', difficulty: 'Intermediate', genre: 'Pop Rock', module: 6, ageGroup: 'Any' },
  { id: 's52', title: 'The Night We Met', artist: 'Lord Huron', difficulty: 'Intermediate', genre: 'Indie', module: 6, ageGroup: 'Any' },
  { id: 's220', title: 'Golden Hour', artist: 'JVKE', difficulty: 'Intermediate', genre: 'Pop', module: 6, ageGroup: 'Any' },
  { id: 's221', title: 'Heat Waves', artist: 'Glass Animals', difficulty: 'Intermediate', genre: 'Pop', module: 6, ageGroup: 'Youth' },
  { id: 's222', title: 'As It Was', artist: 'Harry Styles', difficulty: 'Beginner', genre: 'Pop', module: 6, ageGroup: 'Youth' },
  { id: 's317', title: 'drivers license', artist: 'Olivia Rodrigo', difficulty: 'Intermediate', genre: 'Pop', module: 6, ageGroup: 'Youth' },
  { id: 's318', title: 'Chasing Cars', artist: 'Snow Patrol', difficulty: 'Intermediate', genre: 'Indie Rock', module: 6, ageGroup: 'Any' },
  { id: 's319', title: 'Memories', artist: 'Maroon 5', difficulty: 'Beginner', genre: 'Pop', module: 6, ageGroup: 'Any' },
  { id: 's320', title: 'Stay (piano)', artist: 'The Kid LAROI & Justin Bieber', difficulty: 'Beginner', genre: 'Pop', module: 6, ageGroup: 'Youth' },
  { id: 's321', title: 'Circles', artist: 'Post Malone', difficulty: 'Beginner', genre: 'Pop', module: 6, ageGroup: 'Youth' },

  // ── MÓDULO 7 — ARMADURAS Y CÍRCULO DE QUINTAS ────────────────────────────
  { id: 's19', title: 'Counting Stars', artist: 'OneRepublic', difficulty: 'Beginner', genre: 'Pop Rock', module: 7, ageGroup: 'Youth' },
  { id: 's21', title: 'With or Without You', artist: 'U2', difficulty: 'Beginner', genre: 'Rock', module: 7, ageGroup: 'Adults' },
  { id: 's22', title: "Don't Look Back in Anger", artist: 'Oasis', difficulty: 'Beginner', genre: 'Rock', module: 7, ageGroup: 'Adults' },
  { id: 's223', title: 'Take Me Home, Country Roads', artist: 'John Denver', difficulty: 'Beginner', genre: 'Folk', module: 7, ageGroup: 'Any' },
  { id: 's322', title: 'Let It Go (Frozen)', artist: 'Idina Menzel / Disney', difficulty: 'Intermediate', genre: 'Film / Musical', module: 7, ageGroup: 'Kids' },
  { id: 's323', title: 'Yesterday', artist: 'The Beatles', difficulty: 'Intermediate', genre: 'Classic Pop', module: 7, ageGroup: 'Adults' },
  { id: 's324', title: 'La Vie en Rose', artist: 'Édith Piaf', difficulty: 'Intermediate', genre: 'French Chanson', module: 7, ageGroup: 'Adults' },
  { id: 's325', title: 'Thriller (piano intro)', artist: 'Michael Jackson', difficulty: 'Intermediate', genre: 'Pop', module: 7, ageGroup: 'Any' },

  // ── MÓDULO 8 — INVERSIONES Y VOICINGS ────────────────────────────────────
  { id: 's50', title: 'Stereo Hearts (piano)', artist: 'Gym Class Heroes', difficulty: 'Beginner', genre: 'Pop', module: 8, ageGroup: 'Youth' },
  { id: 's25', title: 'No Woman No Cry', artist: 'Bob Marley', difficulty: 'Beginner', genre: 'Reggae', module: 8, ageGroup: 'Adults' },
  { id: 's224', title: 'Pachelbel Canon (pop voicings)', artist: 'Pachelbel', difficulty: 'Intermediate', genre: 'Classical', module: 8, ageGroup: 'Any' },
  { id: 's225', title: 'Someone You Loved', artist: 'Lewis Capaldi', difficulty: 'Intermediate', genre: 'Pop', module: 8, ageGroup: 'Any' },
  { id: 's326', title: 'Lean on Me', artist: 'Bill Withers', difficulty: 'Beginner', genre: 'Soul', module: 8, ageGroup: 'Any' },
  { id: 's327', title: 'Fields of Gold', artist: 'Sting', difficulty: 'Intermediate', genre: 'Pop', module: 8, ageGroup: 'Adults' },
  { id: 's328', title: 'Have You Ever Seen the Rain', artist: 'Creedence Clearwater Revival', difficulty: 'Beginner', genre: 'Rock', module: 8, ageGroup: 'Any' },

  // ── MÓDULO 9 — AMBAS MANOS ───────────────────────────────────────────────
  { id: 's53', title: 'Perfect', artist: 'Ed Sheeran', difficulty: 'Intermediate', genre: 'Pop', module: 9, ageGroup: 'Any' },
  { id: 's54', title: 'All of Me', artist: 'John Legend', difficulty: 'Intermediate', genre: 'R&B', module: 9, ageGroup: 'Any' },
  { id: 's55', title: 'The Scientist', artist: 'Coldplay', difficulty: 'Intermediate', genre: 'Rock', module: 9, ageGroup: 'Any' },
  { id: 's57', title: 'Yellow', artist: 'Coldplay', difficulty: 'Intermediate', genre: 'Rock', module: 9, ageGroup: 'Any' },
  { id: 's59', title: 'Thinking Out Loud', artist: 'Ed Sheeran', difficulty: 'Intermediate', genre: 'Pop', module: 9, ageGroup: 'Any' },
  { id: 's60', title: 'Let It Be', artist: 'The Beatles', difficulty: 'Intermediate', genre: 'Classic Rock', module: 9, ageGroup: 'Any' },
  { id: 's63', title: 'A Thousand Years', artist: 'Christina Perri', difficulty: 'Intermediate', genre: 'Pop', module: 9, ageGroup: 'Any' },
  { id: 's329', title: 'Piano Man', artist: 'Billy Joel', difficulty: 'Intermediate', genre: 'Classic Rock', module: 9, ageGroup: 'Any' },
  { id: 's330', title: 'Your Song', artist: 'Elton John', difficulty: 'Intermediate', genre: 'Classic Pop', module: 9, ageGroup: 'Any' },
  { id: 's331', title: 'Tiny Dancer', artist: 'Elton John', difficulty: 'Intermediate', genre: 'Classic Pop', module: 9, ageGroup: 'Adults' },
  { id: 's332', title: 'Clocks', artist: 'Coldplay', difficulty: 'Intermediate', genre: 'Rock', module: 9, ageGroup: 'Any' },

  // ── MÓDULO 10 — LECTURA MUSICAL (clásico / notado) ───────────────────────
  { id: 's68', title: 'Für Elise', artist: 'Beethoven', difficulty: 'Intermediate', genre: 'Classical', module: 10, ageGroup: 'Any' },
  { id: 's72', title: 'Prelude in C Major', artist: 'J.S. Bach', difficulty: 'Intermediate', genre: 'Classical', module: 10, ageGroup: 'Any' },
  { id: 's78', title: 'Minuet in G', artist: 'Bach (simplified)', difficulty: 'Intermediate', genre: 'Classical', module: 10, ageGroup: 'Any' },
  { id: 's76', title: 'Gymnopédie No.1', artist: 'Satie', difficulty: 'Intermediate', genre: 'Classical', module: 10, ageGroup: 'Adults' },
  { id: 's77', title: 'Canon in D (simplified)', artist: 'Pachelbel', difficulty: 'Intermediate', genre: 'Classical', module: 10, ageGroup: 'Any' },
  { id: 's333', title: 'Marcha Turca (Turkish March)', artist: 'Mozart', difficulty: 'Intermediate', genre: 'Classical', module: 10, ageGroup: 'Any' },
  { id: 's334', title: 'Vals Op.64 No.2 (simplificado)', artist: 'Chopin', difficulty: 'Intermediate', genre: 'Classical', module: 10, ageGroup: 'Adults' },
  { id: 's335', title: 'Sonatina en Sol (Op.49)', artist: 'Beethoven', difficulty: 'Intermediate', genre: 'Classical', module: 10, ageGroup: 'Any' },

  // ── MÓDULO 11 — ACORDES DE SÉPTIMA Y COLOR (jazz / soul / R&B) ───────────
  { id: 's94', title: 'Fly Me to the Moon', artist: 'Frank Sinatra', difficulty: 'Intermediate', genre: 'Jazz', module: 11, ageGroup: 'Adults' },
  { id: 's96', title: 'What a Wonderful World', artist: 'Louis Armstrong', difficulty: 'Intermediate', genre: 'Jazz', module: 11, ageGroup: 'Any' },
  { id: 's58', title: 'Stay With Me', artist: 'Sam Smith', difficulty: 'Intermediate', genre: 'Soul', module: 11, ageGroup: 'Any' },
  { id: 's226', title: 'Sunday Morning', artist: 'Maroon 5', difficulty: 'Intermediate', genre: 'Pop Jazz', module: 11, ageGroup: 'Any' },
  { id: 's227', title: 'Snooze', artist: 'SZA', difficulty: 'Intermediate', genre: 'R&B', module: 11, ageGroup: 'Youth' },
  { id: 's336', title: "Ain't No Sunshine", artist: 'Bill Withers', difficulty: 'Intermediate', genre: 'Soul', module: 11, ageGroup: 'Any' },
  { id: 's337', title: 'Summertime', artist: 'George Gershwin', difficulty: 'Intermediate', genre: 'Jazz', module: 11, ageGroup: 'Adults' },
  { id: 's338', title: 'I Say a Little Prayer', artist: 'Aretha Franklin', difficulty: 'Intermediate', genre: 'Soul', module: 11, ageGroup: 'Adults' },
  { id: 's339', title: 'Just the Two of Us', artist: 'Grover Washington Jr.', difficulty: 'Intermediate', genre: 'Jazz Soul', module: 11, ageGroup: 'Adults' },

  // ── MÓDULO 12 — ESCALAS MENORES Y MODOS ──────────────────────────────────
  { id: 's44', title: 'House of the Rising Sun', artist: 'The Animals', difficulty: 'Intermediate', genre: 'Rock', module: 12, ageGroup: 'Adults' },
  { id: 's228', title: 'Scarborough Fair', artist: 'Traditional (Dorian)', difficulty: 'Intermediate', genre: 'Folk', module: 12, ageGroup: 'Any' },
  { id: 's229', title: 'Mad World (modal)', artist: 'Gary Jules', difficulty: 'Intermediate', genre: 'Alternative', module: 12, ageGroup: 'Any' },
  { id: 's45', title: 'Creep (piano)', artist: 'Radiohead', difficulty: 'Intermediate', genre: 'Alternative', module: 12, ageGroup: 'Any' },
  { id: 's340', title: 'Sultans of Swing (piano) [Dórico]', artist: 'Dire Straits', difficulty: 'Intermediate', genre: 'Rock', module: 12, ageGroup: 'Adults' },
  { id: 's341', title: 'Oye Como Va [Dórico]', artist: 'Santana', difficulty: 'Intermediate', genre: 'Latin Rock', module: 12, ageGroup: 'Any' },
  { id: 's342', title: 'Riders on the Storm [Eólico]', artist: 'The Doors', difficulty: 'Intermediate', genre: 'Rock', module: 12, ageGroup: 'Adults' },

  // ── MÓDULO 13 — ARMONÍA Y PROGRESIONES ───────────────────────────────────
  { id: 's33', title: 'Rolling in the Deep', artist: 'Adele', difficulty: 'Intermediate', genre: 'Soul Pop', module: 13, ageGroup: 'Any' },
  { id: 's42', title: 'In the End (piano)', artist: 'Linkin Park', difficulty: 'Intermediate', genre: 'Rock', module: 13, ageGroup: 'Youth' },
  { id: 's230', title: 'Hotel California (progression)', artist: 'Eagles', difficulty: 'Advanced', genre: 'Rock', module: 13, ageGroup: 'Adults' },
  { id: 's102', title: "Don't Stop Believin'", artist: 'Journey', difficulty: 'Intermediate', genre: 'Rock', module: 13, ageGroup: 'Any' },
  { id: 's343', title: 'September', artist: 'Earth, Wind & Fire', difficulty: 'Intermediate', genre: 'Funk Soul', module: 13, ageGroup: 'Any' },
  { id: 's344', title: 'My Girl', artist: 'The Temptations', difficulty: 'Intermediate', genre: 'Soul', module: 13, ageGroup: 'Adults' },
  { id: 's345', title: 'Valerie', artist: 'Amy Winehouse', difficulty: 'Intermediate', genre: 'Soul', module: 13, ageGroup: 'Any' },
  { id: 's346', title: 'Hit the Road Jack', artist: 'Ray Charles', difficulty: 'Intermediate', genre: 'R&B', module: 13, ageGroup: 'Any' },

  // ── MÓDULO 14 — PEDAL, DINÁMICA Y EXPRESIÓN (baladas) ────────────────────
  { id: 's67', title: 'River Flows in You', artist: 'Yiruma', difficulty: 'Intermediate', genre: 'Neoclassical', module: 14, ageGroup: 'Any' },
  { id: 's70', title: 'Kiss the Rain', artist: 'Yiruma', difficulty: 'Intermediate', genre: 'Neoclassical', module: 14, ageGroup: 'Any' },
  { id: 's74', title: 'Nuvole Bianche', artist: 'Ludovico Einaudi', difficulty: 'Intermediate', genre: 'Neoclassical', module: 14, ageGroup: 'Any' },
  { id: 's66', title: "Comptine d'un autre été", artist: 'Yann Tiersen', difficulty: 'Intermediate', genre: 'Neoclassical', module: 14, ageGroup: 'Any' },
  { id: 's56', title: 'Fix You', artist: 'Coldplay', difficulty: 'Intermediate', genre: 'Rock', module: 14, ageGroup: 'Any' },
  { id: 's347', title: 'Experience', artist: 'Ludovico Einaudi', difficulty: 'Intermediate', genre: 'Neoclassical', module: 14, ageGroup: 'Any' },
  { id: 's348', title: 'Ballade Pour Adeline', artist: 'Richard Clayderman', difficulty: 'Intermediate', genre: 'Neoclassical', module: 14, ageGroup: 'Adults' },
  { id: 's349', title: 'Con te Partirò (piano)', artist: 'Andrea Bocelli', difficulty: 'Intermediate', genre: 'Classical Crossover', module: 14, ageGroup: 'Adults' },
  { id: 's350', title: 'Adagio en Sol menor', artist: 'Albinoni', difficulty: 'Intermediate', genre: 'Classical', module: 14, ageGroup: 'Adults' },

  // ── MÓDULO 15 — DOMINIO DE CANCIONES (avanzado / completo) ───────────────
  { id: 's79', title: 'Moonlight Sonata (1st mov.)', artist: 'Beethoven', difficulty: 'Advanced', genre: 'Classical', module: 15, ageGroup: 'Any' },
  { id: 's80', title: 'Clair de Lune (simplified)', artist: 'Debussy', difficulty: 'Advanced', genre: 'Classical', module: 15, ageGroup: 'Any' },
  { id: 's82', title: 'Interstellar Main Theme', artist: 'Hans Zimmer', difficulty: 'Advanced', genre: 'Film Score', module: 15, ageGroup: 'Any' },
  { id: 's83', title: "He's a Pirate", artist: 'Hans Zimmer', difficulty: 'Advanced', genre: 'Film Score', module: 15, ageGroup: 'Any' },
  { id: 's62', title: 'Shallow', artist: 'Lady Gaga & Bradley Cooper', difficulty: 'Intermediate', genre: 'Pop', module: 15, ageGroup: 'Any' },
  { id: 's86', title: 'Bohemian Rhapsody', artist: 'Queen', difficulty: 'Advanced', genre: 'Rock', module: 15, ageGroup: 'Any' },
  { id: 's231', title: 'Merry-Go-Round of Life', artist: 'Joe Hisaishi', difficulty: 'Advanced', genre: 'Film Score', module: 15, ageGroup: 'Any' },
  { id: 's351', title: 'Nocturno Op.9 No.2', artist: 'Chopin', difficulty: 'Advanced', genre: 'Classical', module: 15, ageGroup: 'Adults' },
  { id: 's352', title: 'La Campanella (simplificada)', artist: 'Liszt', difficulty: 'Advanced', genre: 'Classical', module: 15, ageGroup: 'Adults' },
  { id: 's353', title: 'Rapsodia en Azul (apertura)', artist: 'George Gershwin', difficulty: 'Advanced', genre: 'Classical Jazz', module: 15, ageGroup: 'Adults' },
  { id: 's354', title: 'Pavane', artist: 'Gabriel Fauré', difficulty: 'Advanced', genre: 'Classical', module: 15, ageGroup: 'Adults' },

  // ── MÓDULO 16 — EXPRÉSATE (improvisación / jazz / mundo) ──────────────────
  { id: 's93', title: 'Autumn Leaves', artist: 'Jazz Standard', difficulty: 'Advanced', genre: 'Jazz', module: 16, ageGroup: 'Adults' },
  { id: 's95', title: 'Georgia on My Mind', artist: 'Ray Charles', difficulty: 'Intermediate', genre: 'Jazz Soul', module: 16, ageGroup: 'Adults' },
  { id: 's98', title: 'Blues in C', artist: 'Original / 12-bar Blues', difficulty: 'Intermediate', genre: 'Blues', module: 16, ageGroup: 'Any' },
  { id: 's97', title: 'Pentatonic Improvisation in C', artist: 'Original / Exercise', difficulty: 'Intermediate', genre: 'Improvisation', module: 16, ageGroup: 'Any' },
  { id: 's99', title: 'Despacito (piano version)', artist: 'Luis Fonsi', difficulty: 'Intermediate', genre: 'Latin', module: 16, ageGroup: 'Any' },
  { id: 's103', title: 'Africa (piano)', artist: 'Toto', difficulty: 'Intermediate', genre: 'Pop Rock', module: 16, ageGroup: 'Any' },
  { id: 's355', title: 'Take Five', artist: 'Dave Brubeck Quartet', difficulty: 'Advanced', genre: 'Jazz', module: 16, ageGroup: 'Adults' },
  { id: 's356', title: 'Misty', artist: 'Erroll Garner', difficulty: 'Advanced', genre: 'Jazz', module: 16, ageGroup: 'Adults' },
  { id: 's357', title: 'The Girl from Ipanema', artist: 'João Gilberto / Tom Jobim', difficulty: 'Intermediate', genre: 'Bossa Nova', module: 16, ageGroup: 'Adults' },
  { id: 's358', title: 'Blue in Green', artist: 'Miles Davis', difficulty: 'Advanced', genre: 'Jazz', module: 16, ageGroup: 'Adults' },
];

export const MOTIVATIONAL_QUOTES = {
  kids: [
    '¡Todo gran músico empezó justo donde estás tú. Sigue adelante! 🎹',
    'No solo estás tocando piano — ¡estás creando magia! ✨',
    'La práctica te hace progresar, ¡y estás progresando MUCHÍSIMO! 🌟',
    '¡Tus dedos aprenden algo nuevo cada día! 🎵',
  ],
  youth: [
    'Los músicos de verdad no nacen — se construyen, una sesión de práctica a la vez.',
    'Cada acorde que sabes es una canción que puedes tocar. Sumas acordes cada semana.',
    'Los artistas que amas empezaron con los mismos básicos que estás aprendiendo.',
    'La música es el único idioma que nunca tiene barreras.',
  ],
  adults: [
    'Nunca es tarde para aprender música — y lo estás demostrando cada semana.',
    'El cerebro que aprende piano se vuelve más agudo en todo lo demás. Es una inversión.',
    'Cada sesión de práctica reconecta tu cerebro. Respaldado por la ciencia.',
    'Decidiste empezar. Esa decisión ya te pone delante de todos los que no lo hicieron.',
  ],
};
