// ─── RÜVEL Piano Method — Exercise Library ──────────────────────────────────

export type ExerciseCategory =
  | 'Hanon'
  | 'Scales & Arpeggios'
  | 'Rhythm Patterns'
  | 'Technique Drills'
  | 'Sight Reading';

export type ExerciseDifficulty = 'Starter' | 'Intermediate' | 'Advanced';

export interface Exercise {
  id: string;
  title: string;
  category: ExerciseCategory;
  difficulty: ExerciseDifficulty;
  develops: string[]; // skill tags
  duration: number; // estimated minutes per session
  description: string;
  howTo: string; // brief instruction
  youtubeSearch: string;
  musescoreSearch?: string;
  tempo?: string; // e.g. "Start at 60 BPM, work up to 100"
}

export const EXERCISES: Exercise[] = [
  // ─── HANON ───────────────────────────────────────────────────────────────
  {
    id: 'hanon_1',
    title: 'Hanon No. 1',
    category: 'Hanon',
    difficulty: 'Starter',
    develops: ['Finger independence', 'Evenness', 'Speed'],
    duration: 5,
    description: 'The classic five-finger extension exercise. Ascending and descending pattern using all 5 fingers.',
    howTo: 'Start with RH only at 60 BPM. Then LH only. Then hands together. Increase speed by 5 BPM each day until you reach 100+.',
    youtubeSearch: 'Hanon No 1 piano exercise tutorial slow',
    musescoreSearch: 'Hanon No 1 piano',
    tempo: 'Start 60 BPM → goal 100+ BPM',
  },
  {
    id: 'hanon_2',
    title: 'Hanon No. 2',
    category: 'Hanon',
    difficulty: 'Starter',
    develops: ['Finger independence', 'Evenness', '3rd-4th finger strength'],
    duration: 5,
    description: 'Variation of the 5-finger pattern focusing on the weaker 3rd, 4th, and 5th fingers.',
    howTo: 'Same approach as No. 1. Focus on keeping the 4th and 5th fingers curved — these collapse most easily.',
    youtubeSearch: 'Hanon No 2 piano exercise tutorial',
    musescoreSearch: 'Hanon No 2 piano',
    tempo: 'Start 60 BPM → goal 100 BPM',
  },
  {
    id: 'hanon_3',
    title: 'Hanon No. 3',
    category: 'Hanon',
    difficulty: 'Intermediate',
    develops: ['Finger independence', 'Wrist control', 'Speed'],
    duration: 5,
    description: 'Ascending leaps and extensions. Develops wider stretches and wrist flexibility.',
    howTo: 'Pay special attention to wrist position — it should be level, not drooping. The stretch should come from the fingers, not the wrist.',
    youtubeSearch: 'Hanon No 3 piano exercise tutorial',
    musescoreSearch: 'Hanon No 3 piano',
    tempo: 'Start 60 BPM → goal 96 BPM',
  },
  {
    id: 'hanon_4',
    title: 'Hanon No. 4',
    category: 'Hanon',
    difficulty: 'Intermediate',
    develops: ['Thumb agility', 'Hand crossing', 'Coordination'],
    duration: 5,
    description: 'Introduces crossing the thumb under the hand, essential for scale playing.',
    howTo: 'Practice the thumb-under movement in isolation before adding the full pattern. The thumb should move silently and smoothly.',
    youtubeSearch: 'Hanon No 4 piano exercise thumb under',
    musescoreSearch: 'Hanon No 4 piano',
    tempo: 'Start 60 BPM → goal 96 BPM',
  },
  {
    id: 'hanon_5',
    title: 'Hanon No. 5',
    category: 'Hanon',
    difficulty: 'Intermediate',
    develops: ['3rd and 4th finger strength', 'Independence', 'Legato'],
    duration: 5,
    description: 'Focuses on strengthening the ring and pinky fingers, the weakest pair in most hands.',
    howTo: 'Play with extreme attention to evenness. Every note should be exactly the same volume. Use a recording to check for unevenness.',
    youtubeSearch: 'Hanon No 5 piano exercise 4th 5th finger',
    musescoreSearch: 'Hanon No 5 piano',
    tempo: 'Start 56 BPM → goal 92 BPM',
  },
  {
    id: 'hanon_6',
    title: 'Hanon Nos. 6-10 (Advanced Set)',
    category: 'Hanon',
    difficulty: 'Advanced',
    develops: ['Full hand technique', 'Speed', 'Endurance', 'Tone control'],
    duration: 15,
    description: 'The more advanced Hanon exercises featuring octave stretches, trills, and complex crossing patterns.',
    howTo: 'Work on each exercise separately before running them in sequence. Focus on relaxed arms — tension is the enemy of speed.',
    youtubeSearch: 'Hanon piano exercises 6 7 8 9 10 advanced tutorial',
    musescoreSearch: 'Hanon complete piano exercises',
    tempo: 'Start 60 BPM → goal 108+ BPM',
  },

  // ─── SCALES & ARPEGGIOS ──────────────────────────────────────────────────
  {
    id: 'scale_c_major',
    title: 'C Major Scale — 2 Octaves',
    category: 'Scales & Arpeggios',
    difficulty: 'Starter',
    develops: ['Thumb crossover', 'Evenness', 'Key awareness'],
    duration: 5,
    description: 'The foundational scale — all white keys, one octave then two. The template for all other scales.',
    howTo: 'RH fingering: 1-2-3 then thumb under for 1-2-3-4-5. LH fingering: 5-4-3-2-1 then 3-2-1. Hands together: aim for perfect synchronization.',
    youtubeSearch: 'C major scale piano 2 octaves hands together tutorial',
    musescoreSearch: 'C major scale piano',
    tempo: 'Start 60 BPM → goal 120 BPM',
  },
  {
    id: 'scale_am',
    title: 'A Natural Minor Scale — 2 Octaves',
    category: 'Scales & Arpeggios',
    difficulty: 'Starter',
    develops: ['Minor key awareness', 'Ear training', 'Finger evenness'],
    duration: 5,
    description: 'The relative minor of C major — same fingering, same notes, starting on A. Sounds darker and more emotional.',
    howTo: 'Same fingering as C major but starting on A. Note the different "feel" and sound compared to C major.',
    youtubeSearch: 'A minor scale piano 2 octaves tutorial natural minor',
    musescoreSearch: 'A minor scale piano',
    tempo: 'Start 60 BPM → goal 120 BPM',
  },
  {
    id: 'scale_g_major',
    title: 'G Major Scale',
    category: 'Scales & Arpeggios',
    difficulty: 'Starter',
    develops: ['Sharp key awareness', 'F# control', 'Black key confidence'],
    duration: 5,
    description: 'First scale with one sharp (F#). The thumb crossover happens at a different point than C major.',
    howTo: 'Watch for the F# — it\'s a black key and the finger must adjust position. Practice slowly on the F# transition first.',
    youtubeSearch: 'G major scale piano tutorial 2 octaves',
    musescoreSearch: 'G major scale piano',
    tempo: 'Start 60 BPM → goal 116 BPM',
  },
  {
    id: 'arp_c_major',
    title: 'C Major Arpeggio — 2 Octaves',
    category: 'Scales & Arpeggios',
    difficulty: 'Intermediate',
    develops: ['Hand stretching', 'Thumb agility', 'Chord fluency'],
    duration: 5,
    description: 'C-E-G played as a broken chord up two octaves. Develops the ability to play widely-spaced notes smoothly.',
    howTo: 'The thumb must cross silently under on every C. Wrist rotates slightly to assist the thumb movement. Keep arms relaxed.',
    youtubeSearch: 'C major arpeggio piano 2 octaves tutorial technique',
    musescoreSearch: 'C major arpeggio piano',
    tempo: 'Start 50 BPM → goal 92 BPM',
  },
  {
    id: 'scale_chromatic',
    title: 'Chromatic Scale — Full Keyboard',
    category: 'Scales & Arpeggios',
    difficulty: 'Advanced',
    develops: ['All 12 keys', 'Black key fluency', 'Speed', 'Technical control'],
    duration: 8,
    description: 'Every semitone from one end of the keyboard to the other. All black and white keys in sequence.',
    howTo: 'Fingering: 1-3 on white, 2 or 3 on black. Both hands together. Focus on equal volume between black and white keys — common mistake is accenting the black keys.',
    youtubeSearch: 'chromatic scale piano tutorial fingering hands together',
    musescoreSearch: 'chromatic scale piano fingering',
    tempo: 'Start 60 BPM → goal 132+ BPM',
  },

  // ─── RHYTHM PATTERNS ─────────────────────────────────────────────────────
  {
    id: 'rhythm_cumbia',
    title: 'Cumbia Piano Pattern',
    category: 'Rhythm Patterns',
    difficulty: 'Intermediate',
    develops: ['Latin rhythm', 'Syncopation', 'Left hand independence'],
    duration: 10,
    description: 'The iconic cumbia pattern: bass note on 1, chord stabs on the off-beats. Gives piano a rhythmic, danceable feel.',
    howTo: 'LH: root note on beat 1. RH: chord stab on the "and" of 2 and beat 3. Start very slow — the syncopation is tricky. Use a metronome and count "1 and 2 AND 3 and 4."',
    youtubeSearch: 'cumbia piano rhythm pattern tutorial Latin groove',
    tempo: 'Start 70 BPM → feel 100-120 BPM',
  },
  {
    id: 'rhythm_reggaeton',
    title: 'Reggaeton / Dembow Piano Pattern',
    category: 'Rhythm Patterns',
    difficulty: 'Intermediate',
    develops: ['Urban rhythm', 'Syncopation', 'Chord stabs'],
    duration: 8,
    description: 'The dembow pattern: the "boom-ch-boom-CHAK" that underlies all reggaeton. Applied to piano chord stabs.',
    howTo: 'The key beat is the "and" of beat 2 — the accented off-beat. LH keeps bass note, RH plays chord stab on the accented off-beats.',
    youtubeSearch: 'reggaeton dembow piano pattern tutorial urban groove',
    tempo: 'Start 80 BPM → feel 95-120 BPM',
  },
  {
    id: 'rhythm_bossa_nova',
    title: 'Bossa Nova Piano Pattern',
    category: 'Rhythm Patterns',
    difficulty: 'Intermediate',
    develops: ['Brazilian rhythm', 'Swing feel', 'Two-hand coordination'],
    duration: 10,
    description: 'The classic bossa nova rhythm: jazz harmony meets samba. The "tim-tim-tim, tim-TSCH-tim" pattern.',
    howTo: 'LH: bass note + fifth alternating. RH: chord on beat 1, then syncopated stabs on beats 2.5, 3, 4.5. Listen to João Gilberto — this rhythm is hypnotic when internalized.',
    youtubeSearch: 'bossa nova piano rhythm pattern tutorial jazz Brazilian',
    tempo: 'Start 70 BPM → feel 90-110 BPM',
  },
  {
    id: 'rhythm_salsa',
    title: 'Salsa / Son Montuno Piano Pattern',
    category: 'Rhythm Patterns',
    difficulty: 'Advanced',
    develops: ['Cuban rhythm', 'Montuno pattern', 'Syncopation', 'RH speed'],
    duration: 12,
    description: 'The montuno: a repeated two-bar rhythmic chord pattern that drives salsa music. One of the most iconic piano patterns in Latin music.',
    howTo: 'The montuno uses both hands in syncopated patterns. Start with just the RH montuno chord pattern, then add the LH bass tumbao separately before combining.',
    youtubeSearch: 'salsa piano montuno pattern tutorial Cuban son',
    tempo: 'Start 80 BPM → feel 150-180 BPM',
  },
  {
    id: 'rhythm_blues_shuffle',
    title: 'Blues Shuffle Pattern',
    category: 'Rhythm Patterns',
    difficulty: 'Intermediate',
    develops: ['Blues groove', 'Swing feel', 'Left hand independence'],
    duration: 8,
    description: 'The foundation of blues piano: root-fifth-sixth pattern in the left hand with a shuffle feel. Powers 12-bar blues.',
    howTo: 'LH: play root, then reach up to 5th, then 6th, alternating with the shuffle feel. The "feel" is the key: quarter note, then 2 eighth notes swung (long-short).',
    youtubeSearch: 'blues shuffle piano left hand pattern tutorial 12 bar',
    tempo: 'Start 70 BPM → feel 100-130 BPM',
  },
  {
    id: 'rhythm_waltz',
    title: '3/4 Waltz Accompaniment',
    category: 'Rhythm Patterns',
    difficulty: 'Starter',
    develops: ['3/4 time', 'Left hand pattern', 'Chord transitions'],
    duration: 6,
    description: 'The classic waltz accompaniment: bass note on beat 1, chord on beats 2 and 3. Elegant and foundational.',
    howTo: 'LH: root note on beat 1, then chord on beats 2 and 3 (count: 1-2-3, 1-2-3). RH plays melody. Start with C and F chord only, then add G and Am.',
    youtubeSearch: 'waltz piano accompaniment pattern 3/4 time tutorial',
    tempo: 'Start 80 BPM → feel 126-160 BPM',
  },

  // ─── TECHNIQUE DRILLS ────────────────────────────────────────────────────
  {
    id: 'tech_legato_thirds',
    title: 'Legato Thirds',
    category: 'Technique Drills',
    difficulty: 'Intermediate',
    develops: ['Smooth voice leading', 'Control', 'Tone consistency'],
    duration: 7,
    description: 'Playing two notes a third apart simultaneously in a smooth, connected style. Core technique for romantic piano playing.',
    howTo: 'Play C-E together, slide smoothly to D-F, E-G, F-A, G-B, A-C. Focus on equal tone between both notes — the top note tends to get louder accidentally.',
    youtubeSearch: 'piano legato thirds technique exercise tutorial',
    tempo: 'Start 60 BPM',
  },
  {
    id: 'tech_trills',
    title: 'Trill Exercise (Fingers 1-2, 2-3, 3-4, 4-5)',
    category: 'Technique Drills',
    difficulty: 'Intermediate',
    develops: ['Finger speed', 'Independence', '4th-5th finger strength'],
    duration: 8,
    description: 'Rapid alternation between two adjacent fingers. Essential for ornaments in classical and jazz piano.',
    howTo: 'Start slowly — really slowly. Speed will come naturally. Focus on the relaxed arm. Tension kills trill speed. The 4-5 trill is the hardest — give it extra time.',
    youtubeSearch: 'piano trill exercise tutorial fingers speed technique',
    tempo: 'Start 80 BPM trills → work up to 160+ BPM',
  },
  {
    id: 'tech_octave_jumps',
    title: 'Octave Jumps',
    category: 'Technique Drills',
    difficulty: 'Intermediate',
    develops: ['Large interval accuracy', 'Wrist mobility', 'Dynamic control'],
    duration: 6,
    description: 'Playing the same note/chord an octave apart in rapid succession. Builds coordination for dramatic, orchestral-style playing.',
    howTo: 'Start with just one octave jump (C to C) and back. Wrist leads the jump — the arm follows. Do NOT tense — think of a "throw" rather than a "reach."',
    youtubeSearch: 'piano octave jumps technique exercise wrist tutorial',
    tempo: 'Start 60 BPM',
  },
  {
    id: 'tech_staccato',
    title: 'Staccato vs Legato Control',
    category: 'Technique Drills',
    difficulty: 'Starter',
    develops: ['Touch control', 'Articulation', 'Expressiveness'],
    duration: 5,
    description: 'The contrast between short detached notes (staccato) and smooth connected notes (legato). Essential for expressiveness.',
    howTo: 'Play C-D-E-F-G staccato (very short, bouncy), then repeat legato (smooth, connected). Exaggerate the contrast. Then alternate: staccato one note, legato the next.',
    youtubeSearch: 'staccato legato piano exercise technique tutorial',
    tempo: 'Start 60 BPM',
  },
  {
    id: 'tech_dynamics',
    title: 'Dynamic Gradient Exercise',
    category: 'Technique Drills',
    difficulty: 'Starter',
    develops: ['Volume control', 'Expressiveness', 'Touch sensitivity'],
    duration: 5,
    description: 'Building from very soft (pp) to very loud (ff) and back down across a scale or chord. Develops touch sensitivity.',
    howTo: 'Play C scale going up: start barely audible (pp), get louder on each note until G is very loud (ff), then reverse coming back down. Key: use arm weight, not force.',
    youtubeSearch: 'piano dynamics exercise pp to ff crescendo decrescendo',
    tempo: 'Very slow — 40-60 BPM',
  },
  {
    id: 'tech_chord_inversions',
    title: 'Chord Inversions — All Positions',
    category: 'Technique Drills',
    difficulty: 'Intermediate',
    develops: ['Chord fluency', 'Voice leading', 'Inversion knowledge'],
    duration: 8,
    description: 'Playing a chord in all its positions: root position, 1st inversion, 2nd inversion. Essential for smooth chord changes and voice leading.',
    howTo: 'C major: root = C-E-G, 1st inversion = E-G-C, 2nd inversion = G-C-E. Practice each position, then cycle through them without stopping. Then try all 4 magic chords.',
    youtubeSearch: 'chord inversions piano tutorial C major root first second',
    tempo: 'Start 60 BPM',
  },

  // ─── SIGHT READING ────────────────────────────────────────────────────────
  {
    id: 'sight_level1',
    title: 'Sight Reading — Level 1 (5-note range)',
    category: 'Sight Reading',
    difficulty: 'Starter',
    develops: ['Note reading speed', 'Rhythm reading', 'Hand-eye coordination'],
    duration: 10,
    description: 'Simple melodies using only 5 notes (C-G range). Quarter and half notes only. Perfect for Module 1-2 students.',
    howTo: 'Process: 1) Name all notes before playing. 2) Clap the rhythm. 3) Play very slowly. 4) Never stop — keep going even if you make a mistake. Sight read a new piece every day.',
    youtubeSearch: 'beginner piano sight reading level 1 five note range',
    musescoreSearch: 'beginner piano sight reading exercises grade 1',
    tempo: 'Very slow — accuracy first',
  },
  {
    id: 'sight_level2',
    title: 'Sight Reading — Level 2 (Full Treble Clef)',
    category: 'Sight Reading',
    difficulty: 'Intermediate',
    develops: ['Note reading', 'Rhythm complexity', 'Confidence'],
    duration: 10,
    description: 'Melodies spanning the full treble clef range. Eighth notes introduced. For Module 3-5 students.',
    howTo: 'Same 4-step process but faster. Aim to look ahead — read 2-3 notes ahead of where you\'re playing. This is how professional sight readers work.',
    youtubeSearch: 'piano sight reading level 2 grade 2 3 treble clef exercises',
    musescoreSearch: 'piano sight reading grade 2 exercises',
    tempo: 'Slow but steady — never stop',
  },
  {
    id: 'sight_level3',
    title: 'Sight Reading — Level 3 (Both Hands)',
    category: 'Sight Reading',
    difficulty: 'Advanced',
    develops: ['Two-staff reading', 'Coordination', 'Professional skills'],
    duration: 15,
    description: 'Reading from both treble and bass clef simultaneously. For Module 6+ students. The foundation of professional piano reading.',
    howTo: 'Start by reading just RH, then just LH, then together. Look at the bass clef for the chord shape, treble clef for the melody. Trust muscle memory for the left hand.',
    youtubeSearch: 'piano sight reading both hands grand staff exercises tutorial',
    musescoreSearch: 'piano sight reading grade 3 4 both hands',
    tempo: 'Very slow — count everything',
  },
];

export const EXERCISE_CATEGORIES: ExerciseCategory[] = [
  'Hanon',
  'Scales & Arpeggios',
  'Rhythm Patterns',
  'Technique Drills',
  'Sight Reading',
];

export const EXERCISE_DIFFICULTY_COLORS: Record<ExerciseDifficulty, string> = {
  Starter: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
  Intermediate: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  Advanced: 'bg-rose-500/20 text-rose-400 border-rose-500/30',
};
